version: '3.6'

services:
  origin:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    image: airensoft/ovenmediaengine:latest
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
    network_mode: host
    environment:
    - OME_HOST_IP=192.168.0.160
    - OME_ORIGIN_PORT=9000
    - OME_RTMP_PROV_PORT=1935
    - OME_SRT_PROV_PORT=9999
    restart: always
    volumes:
    - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf