version: '3.6'

services:
  origin:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    image: airensoft/ovenmediaengine:latest
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
    ports:
      # RTMP port for OBS ingestion
      - "1935:1935"
      # OVT port for OBS streaming
      - "9000:9000"
      # SRT port for OBS streaming  
      - "9999:9999/udp"
    environment:
    - OME_HOST_IP=yustream-ome
    - OME_ORIGIN_PORT=9000
    - OME_RTMP_PROV_PORT=1935
    - OME_SRT_PROV_PORT=9999
    restart: always
    volumes:
    - ./origin_conf:/opt/ovenmediaengine/bin/origin_conf
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf